/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  80001: {
    upRegistry: {
      address: "0xc400f6d9A06E822864c75a298F36E8ffF94990C8",
      abi: [
        {
          inputs: [],
          name: "InvalidKeyManager",
          type: "error",
        },
        {
          inputs: [],
          name: "NoPermissionsSet",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "_ups",
          outputs: [
            {
              internalType: "address",
              name: "up",
              type: "address",
            },
            {
              internalType: "address",
              name: "keyManager",
              type: "address",
            },
            {
              internalType: "address",
              name: "upLukso",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_up",
              type: "address",
            },
          ],
          name: "permissions",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_up",
              type: "address",
            },
            {
              internalType: "address",
              name: "_km",
              type: "address",
            },
            {
              internalType: "address",
              name: "_upLukso",
              type: "address",
            },
          ],
          name: "setUp",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "km",
              type: "address",
            },
          ],
          name: "target",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "up",
          outputs: [
            {
              internalType: "address",
              name: "up",
              type: "address",
            },
            {
              internalType: "address",
              name: "keyManager",
              type: "address",
            },
            {
              internalType: "address",
              name: "upLukso",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "upByEOA",
          outputs: [
            {
              internalType: "address",
              name: "up",
              type: "address",
            },
            {
              internalType: "address",
              name: "keyManager",
              type: "address",
            },
            {
              internalType: "address",
              name: "upLukso",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "ups",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "up",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "keyManager",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "upLukso",
                  type: "address",
                },
              ],
              internalType: "struct upRegistry.Profile[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
